"""add_categories

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-17 00:10:18.002413

"""
from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LAUNCH_CATEGORIES: Sequence[tuple[str, str]] = (
    ('Vet visit', 'Notes captured from or about an appointment with the vet'),
    ('Your concern', 'Something the owner has noticed and wants on the record'),
    ('Attachment note', 'Context attached to an uploaded photo, video or document'),
    ('Other', 'Anything that does not fit the categories above'),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('uq_categories_name_alive', 'categories', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###
    categories = sa.table(
        'categories',
        sa.column('id', sa.Uuid()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    op.bulk_insert(
        categories,
        [
            {'id': uuid4(), 'name': name, 'description': description}
            for name, description in LAUNCH_CATEGORIES
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_name_alive', table_name='categories', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('categories')
    # ### end Alembic commands ###
