"""add_roadmap_items_and_votes

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-17 00:16:50.438590

"""
from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LAUNCH_ITEMS: Sequence[tuple[str, str]] = (
    ('Pet Circle', 'Share a pet record with family, a sitter or a co-owner'),
    ('Local resources', 'Find vets, groomers and emergency clinics nearby'),
    ('Longer voice notes', 'Raise the recording limit for longer updates'),
    ('Visit reminders', 'Nudges ahead of vaccinations and routine check-ups'),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_items'))
    )
    op.create_index('uq_roadmap_items_title_alive', 'roadmap_items', ['title'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('roadmap_votes',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], name=op.f('fk_roadmap_votes_item_id_roadmap_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_roadmap_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_votes'))
    )
    op.create_index(op.f('ix_roadmap_votes_item_id'), 'roadmap_votes', ['item_id'], unique=False)
    op.create_index(op.f('ix_roadmap_votes_user_id'), 'roadmap_votes', ['user_id'], unique=False)
    op.create_index('uq_roadmap_votes_item_user', 'roadmap_votes', ['item_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
    roadmap_items = sa.table(
        'roadmap_items',
        sa.column('id', sa.Uuid()),
        sa.column('title', sa.String()),
        sa.column('description', sa.String()),
    )
    op.bulk_insert(
        roadmap_items,
        [
            {'id': uuid4(), 'title': title, 'description': description}
            for title, description in LAUNCH_ITEMS
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_roadmap_votes_item_user', table_name='roadmap_votes')
    op.drop_index(op.f('ix_roadmap_votes_user_id'), table_name='roadmap_votes')
    op.drop_index(op.f('ix_roadmap_votes_item_id'), table_name='roadmap_votes')
    op.drop_table('roadmap_votes')
    op.drop_index('uq_roadmap_items_title_alive', table_name='roadmap_items', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('roadmap_items')
    # ### end Alembic commands ###
