"""add_magic_link_tokens

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-17 01:08:37.191135

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_magic_link_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_link_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_magic_link_tokens_token_hash'))
    )
    op.create_index(op.f('ix_magic_link_tokens_expires_at'), 'magic_link_tokens', ['expires_at'], unique=False)
    op.create_index('ix_magic_link_tokens_user_id_consumed_at', 'magic_link_tokens', ['user_id', 'consumed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_magic_link_tokens_user_id_consumed_at', table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_expires_at'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
