"""add_chat

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-17 01:33:04.295944

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_conversations_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_conversations_pet_id_pets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversations_pet_id'), 'conversations', ['pet_id'], unique=False)
    op.create_index('uq_conversations_pet_alive', 'conversations', ['pet_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('captured_entries',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=120), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_captured_entries_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_captured_entries_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_captured_entries_pet_id_pets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captured_entries'))
    )
    op.create_index(op.f('ix_captured_entries_category_id'), 'captured_entries', ['category_id'], unique=False)
    op.create_index(op.f('ix_captured_entries_conversation_id'), 'captured_entries', ['conversation_id'], unique=False)
    op.create_index('ix_captured_entries_pet_confirmed', 'captured_entries', ['pet_id', 'confirmed_at'], unique=False)
    op.create_index(op.f('ix_captured_entries_pet_id'), 'captured_entries', ['pet_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_emergency_notice', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_chat_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'utc_inserted_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_captured_entries_pet_id'), table_name='captured_entries')
    op.drop_index('ix_captured_entries_pet_confirmed', table_name='captured_entries')
    op.drop_index(op.f('ix_captured_entries_conversation_id'), table_name='captured_entries')
    op.drop_index(op.f('ix_captured_entries_category_id'), table_name='captured_entries')
    op.drop_table('captured_entries')
    op.drop_index('uq_conversations_pet_alive', table_name='conversations', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_conversations_pet_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
