"""add_attachments

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-17 01:38:43.714504

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=400), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('utc_inserted_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utc_modified_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_attachments_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_attachments_pet_id_pets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_attachments_storage_key'))
    )
    op.create_index(op.f('ix_attachments_conversation_id'), 'attachments', ['conversation_id'], unique=False)
    op.create_index('ix_attachments_pet_created', 'attachments', ['pet_id', 'utc_inserted_datetime'], unique=False)
    op.create_index(op.f('ix_attachments_pet_id'), 'attachments', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_pet_id'), table_name='attachments')
    op.drop_index('ix_attachments_pet_created', table_name='attachments')
    op.drop_index(op.f('ix_attachments_conversation_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
