"""add_chat_message_ordinal

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-17 01:59:14.373723

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('ordinal', sa.Integer(), nullable=True))
    # Backfill existing rows in insertion order per conversation before the
    # NOT NULL lands, so an upgrade over live data cannot fail.
    op.execute(
        '''
        UPDATE chat_messages SET ordinal = numbered.rn
        FROM (
            SELECT id, row_number() OVER (
                PARTITION BY conversation_id ORDER BY utc_inserted_datetime, id
            ) AS rn
            FROM chat_messages
        ) AS numbered
        WHERE chat_messages.id = numbered.id
        '''
    )
    op.alter_column('chat_messages', 'ordinal', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'ordinal')
    # ### end Alembic commands ###
