"""drop_user_full_name

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-17 17:17:31.682907

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.execute(
        '''
        UPDATE users SET full_name = left(
            coalesce(nullif(btrim(concat_ws(' ', first_name, last_name)), ''), email), 100
        )
        '''
    )
    op.alter_column('users', 'full_name', existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###
