// AUTO-GENERATED by the agent platform — do not edit.
// PreToolUse(Edit|MultiEdit|Write) ownership guard: blocks edits outside the active role's paths.
// Role: AGENT_ROLE env, else the .role field of the sibling <worktree>.meta.json marker.
// No role = no enforcement (plain sessions unaffected). Exit 2 blocks the tool call and explains.
// This file must stay byte-identical across repos; `agent doctor` verifies that.
import { readFileSync, existsSync, appendFileSync } from 'node:fs'
import { basename, dirname, resolve, join } from 'node:path'

const OWNERSHIP_FILE = "ownership.yaml"

let input
try {
  input = JSON.parse(readFileSync(0, 'utf8'))
} catch {
  process.exit(0)
}
const target = input.tool_input?.file_path
if (!target) process.exit(0)

const cwd = process.cwd()
let role = process.env.AGENT_ROLE || process.env.CLAUDE_ROLE
if (!role) {
  const marker = join(dirname(cwd), basename(cwd) + '.meta.json')
  if (existsSync(marker)) {
    try {
      role = JSON.parse(readFileSync(marker, 'utf8').replace(/^\uFEFF/, '')).role
    } catch {
      /* unreadable marker = no enforcement */
    }
  }
}
if (!role) process.exit(0)

const cwdSlash = cwd.replace(/\\/g, '/').replace(/\/$/, '')
const abs = resolve(cwd, target).replace(/\\/g, '/')
if (!abs.toLowerCase().startsWith(cwdSlash.toLowerCase() + '/')) process.exit(0) // outside the repo
const rel = abs.slice(cwdSlash.length + 1)

const yamlPath = join(cwd, OWNERSHIP_FILE)
if (!existsSync(yamlPath)) {
  console.error(`ownership-guard: role '${role}' is active but ${OWNERSHIP_FILE} is missing — run doctor.`)
  process.exit(2)
}

let def = null
const agents = {}
let cur = null
for (const raw of readFileSync(yamlPath, 'utf8').split('\n')) {
  const line = raw.replace(/(^|\s)#.*$/, '').trimEnd()
  if (!line.trim()) continue
  let m
  if ((m = line.match(/^default:\s*(\S+)/))) def = m[1]
  else if ((m = line.match(/^  ([\w-]+):\s*(\[\])?\s*$/))) {
    cur = m[1]
    agents[cur] = []
  } else if ((m = line.match(/^\s+-\s+(\S+)/)) && cur) agents[cur].push(m[1])
}
if (!def) {
  console.error(`ownership-guard: ${OWNERSHIP_FILE} has no 'default:' — run doctor.`)
  process.exit(2)
}

const toRegex = (p) =>
  new RegExp(
    '^' +
      p
        .replace(/[.+^${}()|[\]\\]/g, '\\$&')
        .replace(/\*\*/g, '\u0000')
        .replace(/\*/g, '[^/]*')
        .replace(/\u0000/g, '.*') +
      '$',
  )
const matches = (rel, p) => toRegex(p).test(rel) || (p.startsWith('**/') && toRegex(p.slice(3)).test(rel))

let owner = def
let best = -1
for (const [agent, patterns] of Object.entries(agents)) {
  for (const p of patterns) {
    if (matches(rel, p) && p.length > best) {
      best = p.length
      owner = agent
    }
  }
}

if (owner !== role) {
  try {
    appendFileSync(
      join(dirname(cwd), basename(cwd) + '.violations.log'),
      `${new Date().toISOString()}\trole=${role}\tpath=${rel}\towner=${owner}\n`,
    )
  } catch {
    /* logging is best-effort */
  }
  console.error(
    `ownership-guard: ${rel} is owned by '${owner}', you are '${role}'. STOP editing this file. ` +
      `Record the needed change as a proposal for '${owner}' in your handoff instead.`,
  )
  process.exit(2)
}
